export { ChannelContentConfig } from '../../common/types'
export { default as CHANNEL_CONFIG } from '../../common/channel_config'
export const API_1 = 'api/v1'
export const ERROR_FIELDS_REQUIRED = 'Все поля обязательны для заполнения'
export const ERROR_USER_NOT_FOUND = 'Не удалось получить данные о пользователе'
export const ERROR_USER_ALREADY_EXISTS = 'Пользователь с таким именем уже существует'
export const ERROR_USER_DONT_EXISTS = 'Пользователя с таким именем не существует'
export const ERROR_WRONG_CREDENTIALS = 'Неправильное имя пользователя или пароль'
export const ERROR_NOT_ENOUGH_DATA = 'Недостаточно данных для выполнения запроса'
export const ERROR_CONFIG_NOT_FOUND = 'Не удалось загрузить конфигурацию для выбранного канала'